### ISSUE TITLE
Integrate changelog with the rest of the eco system

### ISSUE THREAD

**Issue by jaseemabid** [openshiftio/saasherder#42]
PR #41 added a sub command called changelog to generate consolidated changelog for all the services that saashreder updated. This needs to be integrated with the rest of the system (a jenkins job maybe?) so that the information is presented wherever its needed.

**Comment by jaseemabid** [comment]
Are the jenkins jobs for this all defined in https://github.com/almighty/almighty-jobs/blob/master/devtools-ci-index.yaml ?

**Comment by kbsingh** [comment]
@jaseemabid they should be. All the promote-to-prod jobs should be there.

**Comment by jaseemabid** [comment]
xref https://github.com/openshiftio/openshift.io/issues/1420

**Comment by maorfr** [comment]
closing as stale
