### ISSUE TITLE
Add validation scopes in saasherder

### ISSUE THREAD

**Issue by kbsingh** [openshiftio/saasherder#45]
When saasherder deploys content, we should be able to validate the target is ready to accept the content being deployed. For this we should have some sanity testing rules, configureable simply.

this might include tests like : 
- validate all Config Map Var's being called for are present in the target namespace before deployment
- validate all secrets requested in the deployment are present in the target namespace

these tests should be configureable at a few different levels : 
- service level, ie at the saas-<role>.git repo level, for rules that need to apply to each deployment in the service 
- at the component level, for each deployment in the service for validations that need to run at the deployment specific level.
- generic validations that are always run ( eg. for the examples mentioned above, we would always want to make sure that templated content is available for the deployment to succeed )

**Comment by jmelis** [comment]
Merged by: https://github.com/openshiftio/saasherder/pull/59
