### ISSUE TITLE
"templating with parameters failed, trying without"

### ISSUE THREAD

**Issue by msrb** [openshiftio/saasherder#47]
In https://ci.centos.org/view/Devtools/job/devtools-saas-analytics-promote-to-prod-test/187/console, I see following:

```
INFO:saasherder.saasherder:oc process --local --output yaml -f bay-templates/worker-ingestion.yaml IMAGE_TAG=637034f SENTRY_DSN=https://ab4cf0c4de874c6391c9af9015b492e5:4cd47da8edd643c6b9371dcec6b5da07@errortracking.prod-preview.openshift.io/19 WORKER_EXCLUDE_QUEUES=GraphImporterTask WORKER_ADMINISTRATION_REGION=ingestion REPLICAS=10 > bay-20180222_111137/worker-ingestion.yaml
error: unknown parameter name "SENTRY_DSN"
WARNING:saasherder.saasherder:Templating of bay-templates/worker-ingestion.yaml with parameters failed, trying without
```

The CI build succeeded despite the fact that one of the parameters was not valid. But what's more concerning is the warning which follows: "Templating of bay-templates/worker-ingestion.yaml with parameters failed, trying without".

I think it would be better to fail here instead of trying to process the template again, without parameters. Ignoring parameters from saas-{analytics,openshiftio} [yaml files](https://github.com/openshiftio/saas-analytics/blob/master/bay-services/worker.yaml#L27-L33) can lead to totally unexpected deployment configurations as default values from templates will be used.

**Comment by maorfr** [comment]
seems to be closed by #71
