### ISSUE TITLE
Create "verify" job for saas-* promotions

### ISSUE THREAD

**Issue by jmelis** [openshiftio/saasherder#48]
Quoting @vpavlin:

> Currently there is no way to block PR merges for saas-* repos to stop production promotion.
>
> Let's come up with a job which will verify whether new commit hash actually comes from successful CI job and make this job block merging. This way, if we need to prevent merging, we can just "fail" or disable the job.
>
> (I think this could work)

**Comment by vpavlin** [comment]
There is a PR test job already https://ci.centos.org/view/Devtools/job/devtools-saas-openshiftio-promote-to-prod-test/ - and it at least verify that the image, we would like to deploy, exist.

It does not block merges, which might be something to consider

And of course, it could be extended

**Comment by maorfr** [comment]
done using `saasherder label` and querying for the output label selector
