### ISSUE TITLE
Feature: code delta metrics in SaaS changes report

### ISSUE THREAD

**Issue by xyntrix** [openshiftio/saasherder#61]
It may be interesting to represent in a succinct way, change deltas in the SaaS changes report. I may commit 20 commits but only end up changing 3 lines on one file, but these 20 commits may seem like a lot of churn.  It might be nice to reference a summary of metrics for each repo, such as:
- Total files modified
- Total lines +added, -removed, *changed(?)

As a bonus, if we expand these metrics to be represented through a small time series graph we can then also provide context around day-to-day or report-to-report change activity. 

This data may be already available from GitHub's report/api interfaces.

Ex: (insights -> code frequency)
![image](https://user-images.githubusercontent.com/33727536/38618636-1b3d1760-3d4f-11e8-9f6b-1f290c9b65e5.png)

**Comment by xyntrix** [comment]
Note: I'd want to ideally see this very minimally represented.. so that the e-mail report doesn't become too eye-aggressive. A tiny spark-line style representation is likely acceptable.

**Comment by maorfr** [comment]
closing as stale
