### ISSUE TITLE
Incorrect template generation when variables that do not exist in the template are added

### ISSUE THREAD

**Issue by jmelis** [openshiftio/saasherder#65]
This issue was triggered when this saasherder service definition has live:
https://github.com/openshiftio/saas-openshiftio/blob/3850f65a5d5f30bb94c5f59c48f8705cc7cd032b/dsaas-services/fabric8-ui.yaml

But in the OpenShift template didn't have the `IMAGE` parameter at that time:
https://github.com/fabric8-ui/fabric8-ui/blob/c9accf6e5385cfbc976a9c276e634d9ae76c0d43/openshift/fabric8-ui.app.yaml

The unexpected result was that the parameters that were defined: `k8s_api_server_base_path`, etc, were empty.

When `IMAGE` was removed from the saasherder service definition, the parameter generation worked correctly again.

**Comment by jmelis** [comment]
I dislike the way it worked before, in particular the `except` part:
https://github.com/openshiftio/saasherder/blob/22330dbcb292413b771988c1f1b2a0963593e4ad/saasherder/saasherder.py#L312-L324

Before the change, if one of the parameters did not exist, it ran `oc process` without any parameters whatsoever and it didn't fail.

With [this change](https://github.com/openshiftio/saasherder/commit/e3c2cc19f271082bc4e6d8cd603ea29c320c5d91)  it will apply all the parameters that actually exist and ignore the rest. I would say that it's better to apply those that exist rather than dropping all of them. Another option I would also like is to fail entirely.

From the latest builds:

- https://ci.centos.org/view/Devtools/job/devtools-saas-analytics-promote-to-prod/351/consoleText
- https://ci.centos.org/view/Devtools/job/devtools-saas-chat-promote-to-prod/16/consoleText
- https://ci.centos.org/view/Devtools/job/devtools-saas-launchpad-promote-to-prod/165/consoleText
- https://ci.centos.org/view/Devtools/job/devtools-saas-openshiftio-promote-to-prod/881/consoleText

the only place with this shows up is here:

    INFO:saasherder.saasherder:oc process  --output yaml -f ./dsaas-templates/redirector.yaml IMAGE_TAG=latest > dsaas-20180516_035905/redirector.yaml
    error: unknown parameter name "IMAGE_TAG"
    WARNING:saasherder.saasherder:Templating of ./dsaas-templates/redirector.yaml with parameters failed, trying without

@kbsingh: what would you do? Keep the change as is, or fail the job if one of the parameters does not exist?

**Comment by vpavlin** [comment]
Yeah, this is definitely broken - the safest is to fail entirely - anything else can cause unpredictable behaviour

**Comment by vpavlin** [comment]
Also, @msrb already filed the same issue here:) https://github.com/openshiftio/saasherder/issues/47

**Comment by jmelis** [comment]
@vpavlin totally agree and thanks for the letting me know about the other issue, I missed that :)

I will change this to fail entirely. Thanks!
